<?php

/**
 * @var \Tco\Checkout\Block\Adminhtml\Order\View\Info\TransactionDetails $block
 */
$payment = $block->getPayment();
$orderNumber = $payment->getAdditionalInformation('tco_order_number');
?>
<?php if (!empty($orderNumber)): ?>
    <br/>
    <div class="admin__page-section-item-title">
        <span class="title"><?php echo $block->escapeHtml(__('2Checkout Order Details')); ?></span>
    </div>

    <div class="admin__page-section-item-content">
        <div class="order-payment-additional">
            <?php if(!empty($orderNumber)): ?>
                <?php echo $block->escapeHtml(__('Order Number')); ?>:
                <?php echo $block->escapeHtml($orderNumber); ?>
                </br>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
