<?php

/**
 * @var \Tco\Checkout\Block\Adminhtml\Order\View\Info\TransactionDetails $block
 */
$payment = $block->getPayment();
$orderNumber = $payment->getAdditionalInformation('tco_order_number');
$orderStatus = $payment->getAdditionalInformation('tco_order_status');
?>
<?php if (!empty($orderNumber)): ?>
    <br/>
    <div class="admin__page-section-item-title">
        <span class="title"><?= $block->escapeHtml(__('2Checkout Order Details')); ?></span>
    </div>

    <div class="admin__page-section-item-content">
        <div class="order-payment-additional">
            <?php if (!empty($orderNumber)): ?>
                <?= $block->escapeHtml(__('Order Number')); ?>:
                <?= $block->escapeHtml($orderNumber); ?>
                </br>
            <?php endif; ?>
            <?php if (!empty($orderStatus)): ?>
                <?= $block->escapeHtml(__('Order Status')); ?>:
                <?= $block->escapeHtml($orderStatus); ?>
                </br>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
